import { FaBitcoin } from "react-icons/fa";
import { RxDashboard } from "react-icons/rx";
import { GrTransaction } from "react-icons/gr";
import { MdOutlineCategory } from "react-icons/md";
import { MdAccountCircle } from "react-icons/md";
import { IoMdSettings } from "react-icons/io";
import { IoMdLogOut } from "react-icons/io";
import { IoMdTrendingUp } from "react-icons/io";
import { GiExpense } from "react-icons/gi";
import { FcMoneyTransfer } from "react-icons/fc";
import { SiFreelancermap } from "react-icons/si";
import { AiOutlineStock } from "react-icons/ai";
import { PiPiggyBank } from "react-icons/pi";
import { FaYoutube } from "react-icons/fa";
import { FaCreditCard } from "react-icons/fa";
import { FaUsers } from "react-icons/fa";
import { FaIndianRupeeSign } from "react-icons/fa6";
import { SlCalender } from "react-icons/sl";
import { FaCartPlus } from "react-icons/fa";
import { RiTakeawayFill } from "react-icons/ri";
import { GiClothes } from "react-icons/gi";
import { SiBookstack } from "react-icons/si";
import { FaTrash } from "react-icons/fa";
import { IoFastFood } from "react-icons/io5";
import { FaBriefcaseMedical } from "react-icons/fa";
import { FaTv } from "react-icons/fa";
import { FaRegCircle } from "react-icons/fa";


export const dashboard = <RxDashboard />
export const transactions = <GrTransaction />
export const categories = <MdOutlineCategory />
export const accounts = <MdAccountCircle />
export const settings = <IoMdSettings />
export const logout = <IoMdLogOut />    
export const trend = <IoMdTrendingUp />
export const expenses = <GiExpense />
export const money = <FcMoneyTransfer />
export const freelance = <SiFreelancermap />
export const stocks = <AiOutlineStock />
export const piggy = <PiPiggyBank />
export const yt = <FaYoutube />
export const card = <FaCreditCard />
export const users = <FaUsers />
export const rupee = <FaIndianRupeeSign />
export const calender = <SlCalender />
export const plus = <FaCartPlus />
export const trash = <FaTrash />;
export const signout = <IoMdLogOut />
export const takeaway = <RiTakeawayFill />
export const clothing = <GiClothes />
export const book = <SiBookstack />
export const food = <IoFastFood />
export const medical = <FaBriefcaseMedical />
export const tv = <FaTv />
export const circle = <FaRegCircle />
export const bitcoin = <FaBitcoin />;